// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteForm struct {
	ID string `json:"id"`
}

type EmailRecipiant struct {
	ParticipantID string `json:"participantID"`
	Email         string `json:"email"`
}

type Feedback struct {
	ID            string `json:"id"`
	QuestionTitle string `json:"questionTitle"`
	QuestionType  string `json:"questionType"`
	Response      string `json:"response"`
	Stage         string `json:"stage"`
}

type Form struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Participants []*Participant `json:"participants"`
	Questions    []*Question    `json:"questions"`
	TimeSent     string         `json:"timeSent"`
	TenderID     string         `json:"tenderID"`
	Description  string         `json:"description"`
	Subject      string         `json:"subject"`
	Message      string         `json:"message"`
	AimID        string         `json:"aimID"`
	Stage        *string        `json:"stage"`
}

type NewEmail struct {
	Participants []*EmailRecipiant `json:"participants"`
	Message      string            `json:"message"`
	Subject      string            `json:"subject"`
}

type NewFeedback struct {
	FormID        string `json:"formID"`
	ParticipantID string `json:"participantID"`
	QuestionID    string `json:"questionID"`
	Response      string `json:"response"`
	Stage         string `json:"stage"`
	Longitude     string `json:"longitude"`
	Latitude      string `json:"latitude"`
	QuestionTitle string `json:"questionTitle"`
	QuestionType  string `json:"questionType"`
}

type NewForm struct {
	Title        string            `json:"title"`
	Participants []*NewParticipant `json:"participants"`
	Questions    []*NewQuestion    `json:"questions"`
	TenderID     string            `json:"tenderID"`
	Description  string            `json:"description"`
	Subject      string            `json:"subject"`
	Message      string            `json:"message"`
	AimID        string            `json:"aimID"`
}

type NewOption struct {
	Rank        int    `json:"rank"`
	Description string `json:"description"`
}

type NewParticipant struct {
	Email     string         `json:"email"`
	Feedback  []*NewFeedback `json:"feedback"`
	Latitude  *string        `json:"latitude"`
	Longitude *string        `json:"longitude"`
}

type NewQuestion struct {
	Title     string         `json:"title"`
	InputType string         `json:"inputType"`
	Options   []*NewOption   `json:"options"`
	Min       int            `json:"min"`
	Max       int            `json:"max"`
	Feedback  []*NewFeedback `json:"feedback"`
}

type Option struct {
	Rank        int    `json:"rank"`
	Description string `json:"description"`
}

type Participant struct {
	ID        string      `json:"id"`
	Email     string      `json:"email"`
	Feedback  []*Feedback `json:"feedback"`
	Latitude  *string     `json:"latitude"`
	Longitude *string     `json:"longitude"`
}

type Question struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	InputType string      `json:"inputType"`
	Options   []*Option   `json:"options"`
	Min       int         `json:"min"`
	Max       int         `json:"max"`
	Feedback  []*Feedback `json:"feedback"`
}

type UpdateQuestion struct {
	ID        string       `json:"id"`
	FormID    string       `json:"formID"`
	Title     string       `json:"title"`
	InputType string       `json:"inputType"`
	Options   []*NewOption `json:"options"`
	Min       int          `json:"min"`
	Max       int          `json:"max"`
}
